---
- name: Upgrade NXOS Router Firmware
  hosts: nxos
  connection: network_cli
  gather_facts: no
  vars:
    connect_timeout: 600
    command_timeout: 600
    compliant_nxos_version: 16.08.01a
    os_file: "/firmware/nxos/system-image-filename.bin"
    kickstart_file: "/firmware/nxos/kickstart-filename.bin"

  tasks:
    - name: Gather switch facts
      nxos_facts:

    - name: Check whether correct OS is already installed
      fail:
        msg: "Nothing to upgrade"
      when: compliant_nxos_version == ansible_net_version

   - name: Copy over nxos os image file
     cli_command:
       command: "copy scp://{{remote_user}}@{{remote_server}}/{{os_file}} bootflash/{{filename}} vrf {{management}}"
       prompt:
         - "{{username}}@"
       answer:
         - "{{scp_password}}"

   - name: Copy over nxos kickstart file
     cli_command:
       command: "copy scp://{{remote_user}}@{{remote_server}}/{{kickstart_file}} bootflash/{{filename}} vrf {{management}}"
       prompt:
         - "{{username}}@"
       answer:
         - "{{scp_password}}"


    # - name: run multiple commands and evaluate the output
    #   nxos_command:
    #     commands:
    #       - show install all impact kickstart n3500-uk9-kickstart.6.0.2.A8.10a.bin system n3500-uk9.6.0.2.A8.10a.bin
    #   register: nxos_command_output

    - name: Check MD5 Sum of os image file
      nxos_command:
        commands:
          - "show file bootflash:{{os_file}} md5sum"
      register: os_output

    - name: Check MD5 Sum of kickstart file
      nxos_command:
        commands:
          - "show file bootflash:{{kickstart_file}} md5sum"
      register: kickstart_output

    - block:
      - name: INSTALL NXOS OS
        nxos_install_os:
          system_image_file: n3500-uk9.6.0.2.A8.10a.bin
          kickstart_image_file: n3500-uk9-kickstart.6.0.2.A8.10a.bin
      when:
        - kickstart_output['results'][0]['stdout'][0]['file_content_md5sum'][:-1] == "{{ kickstart_file.md5 }}"
        - os_output['results'][0]['stdout'][0]['file_content_md5sum'][:-1] == "{{ os_file.md5 }}"

      rescue:

      - name: WAITING FOR DEVICE TO PERFORM ALL UPGRADE CHECKS AND STARTS REBOOT
        wait_for:
          port: 22
          state: stopped
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"

      - name: REBOOT IN PROGRESS - WAITING FOR DEVICE TO COME BACK ONLINE
        wait_for:
          port: 22
          state: started
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"
