---
- name: Upgrade NXOS Router Firmware
  hosts: nxos
  connection: network_cli
  gather_facts: no
  vars:
    connect_timeout: 600
    command_timeout: 600
    compliant_nxos_version: 16.08.01a
    os_file: "/firmware/nxos/system-image-filename.bin"
    kickstart_file: "/firmware/nxos/kickstart-filename.bin"

  tasks:
    - name: Gather switch facts
      nxos_facts:

    - name: Check whether correct OS is already installed
      debug:
        msg: "Nothing to upgrade for {{ inventory_hostname }}"
      when: compliant_nxos_version == ansible_net_version

   - block:
     - name: Copy over nxos os image file
       cli_command:
         command: "copy scp://{{remote_user}}@{{remote_server}}/{{os_file}} bootflash/{{filename}} vrf {{management}}"
         prompt:
           - "{{username}}@"
         answer:
           - "{{scp_password}}"

     - name: Copy over nxos kickstart file
       cli_command:
         command: "copy scp://{{remote_user}}@{{remote_server}}/{{kickstart_file}} bootflash/{{filename}} vrf {{management}}"
         prompt:
           - "{{username}}@"
         answer:
           - "{{scp_password}}"

      - name: INSTALL NXOS OS
        nxos_install_os:
          system_image_file: n3500-uk9.6.0.2.A8.10a.bin
          kickstart_image_file: n3500-uk9-kickstart.6.0.2.A8.10a.bin

      - name: WAITING FOR DEVICE TO PERFORM ALL UPGRADE CHECKS AND STARTS REBOOT
        wait_for:
          port: 22
          state: stopped
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"

      - name: REBOOT IN PROGRESS - WAITING FOR DEVICE TO COME BACK ONLINE
        wait_for:
          port: 22
          state: started
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"

      when: compliant_nxos_version != ansible_net_version

    - name: Gather switch facts
      nxos_facts:

    - name: VERIFY CURRENT VERSION IS EXPECTED VERSION
      assert:
        that:
          - compliant_nxos_version == ansible_net_version
