---
- name: Upgrade NXOS Router Firmware
  hosts: nxos
  connection: network_cli
  gather_facts: no
  vars:
    connect_timeout: 600
    command_timeout: 600
    compliant_nxos_version: 16.08.01a

  tasks:
    - name: GATHER ROUTER FACTS
      nxos_facts:

    - name: CHECK WHETHER CORRECT OS IS ALREADY INSTALLED
      fail:
        msg: "Nothing to upgrade"
      when: compliant_nxos_version == ansible_net_version

    # The scp server has to be enabled to transfer the configuration file to
    # the remote device in order to load it onto the device
    - name: enable the nxos scp server
      cli_config:
        config: "feature scp-server"

    - name: COPY OVER NXOS IMAGE
      nxos_file_copy:
        file_pull: True
        local_file: "system-image-filename.bin"
        local_filr_directory: "bootflash:"
        remote_file: "/firmware/ios/system-image-filename.bin"
        remote_scp_server: "192.168.0.1"
        remote_scp_server_user: "myUser"
        remote_scp_server_password: "myPassword"


    # - name: WAIT FOR FILE TO BE COPIED OVER

    - name: COPY OVER NXOS KICKSTART IMAGE
      nxos_file_copy:
        file_pull: True
        local_file: "system-kickstart_image-filename.bin"
        local_filr_directory: "bootflash"
        remote_file: "/firmware/ios/system-kickstart_image-filename.bin"
        remote_scp_server: "192.168.0.1"
        remote_scp_server_user: "myUser"
        remote_scp_server_password: "myPassword"

   - name: COPY OVER NXOS KICKSTART IMAGE
     cli_command:
       command: "copy scp://{{remote_user}}@{{remote_server}}/{{remote_file}} bootflash/{{filename}} vrf {{management}}"

    # - name: WAIT FOR FILE TO BE COPIED OVER

    - name: run multiple commands and evaluate the output
      nxos_command:
        commands:
          - show install all impact kickstart n3500-uk9-kickstart.6.0.2.A8.10a.bin system n3500-uk9.6.0.2.A8.10a.bin
      register: nxos_command_output

    - block:
      - name: INSTALL NXOS OS
        nxos_install_os:
          system_image_file: n3500-uk9.6.0.2.A8.10a.bin
          kickstart_image_file: n3500-uk9-kickstart.6.0.2.A8.10a.bin
      when: nxos_command_output.results[0].find("FAILED") == -1

      rescue:

      - name: WAITING FOR DEVICE TO PERFORM ALL UPGRADE CHECKS AND STARTS REBOOT
        wait_for:
          port: 22
          state: stopped
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"

      - name: REBOOT IN PROGRESS - WAITING FOR DEVICE TO COME BACK ONLINE
        wait_for:
          port: 22
          state: started
          timeout: 300
          delay: 60
          host: "{{ inventory_hostname }}"
